name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: remove repo
      run: rm -rf /var/www/mural-de-fotos

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy to destiny
      run: cp -r . /var/www/mural-de-fotos
